### ISSUE TITLE
Unable to set LOG_LEVEL in docker compose

### ISSUE THREAD

**Issue by itsallyours** [Majorfi/immich-stack#11]
Using a standard docker-compose template, I added LOG_LEVEL and LOG_FORMAT directly to the yaml.

```
services:
  immich-stack:
    container_name: immich_stack
    # Use Docker Hub image (recommended for Portainer)
    image: majorfi/immich-stack:main # or :latest after next release
    # Or use GitHub Container Registry
    # image: ghcr.io/majorfi/immich-stack:latest
    environment:
      - API_KEY=${API_KEY} # Can be a single key or comma-separated for multiple users
      - API_URL=${API_URL:-http://immich-server:2283/api}
      - DRY_RUN=${DRY_RUN:-false}
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
      - RESET_STACKS=${RESET_STACKS:-false}
      - CONFIRM_RESET_STACK=${CONFIRM_RESET_STACK}
      - REPLACE_STACKS=${REPLACE_STACKS:-false}
      - PARENT_FILENAME_PROMOTE=${PARENT_FILENAME_PROMOTE:-edit}
      - PARENT_EXT_PROMOTE=${PARENT_EXT_PROMOTE:-.jpg,.dng}
      - WITH_ARCHIVED=${WITH_ARCHIVED:-false}
      - WITH_DELETED=${WITH_DELETED:-false}
      - RUN_MODE=${RUN_MODE:-once}
      - CRON_INTERVAL=${CRON_INTERVAL:-86400}
    volumes:
      - ./logs:/app/logs
    restart: on-failure
```

when it runs it still stays in INFO and not JSON:

```
WARN[0000] The "CONFIRM_RESET_STACK" variable is not set. Defaulting to a blank string. 
WARN[0000] /media/me/data/docker/immich/immich-stack/docker-compose.yaml: `version` is obsolete 
[+] Running 1/0
 ✔ Container immich_stack  Created                                                                                                                                                         0.0s 
Attaching to immich_stack
immich_stack  | level=info msg="====================================================================================="
immich_stack  | level=info msg="Running for user: user (user@example.com)"
immich_stack  | level=info msg="====================================================================================="
immich_stack  | level=info msg="Running in once mode"
immich_stack  | level=info msg="📚 42819 assets in a stack with 2 assets"
immich_stack  | level=info msg="📚 13 assets in a stack with 3 assets"
immich_stack  | level=info msg="📚 Fetched 42832 stacks"
immich_stack  | level=info msg="⬇️  Fetching assets:"
immich_stack  | level=info msg="🌄 343768 assets fetched"
immich_stack exited with code 0
```

I ultimately was trying to debug many assets not being stacked.  I have 500K files and expected about 125K stacks because of JPG/RAW pairs.  Only I have 42K total stacks.
