### ISSUE TITLE
Permissions issue with multiple users

### ISSUE THREAD

**Issue by colin715** [Majorfi/immich-stack#6]
[docker_logs.txt](https://github.com/user-attachments/files/20050632/docker_logs.txt)

I've created API keys for both me and my wife and am running two separate docker containers with our respective API keys. Everything works as expected for my wife's instance, but doesn't seem to be working for mine.  When looking at the logs, it appears that both instances are only processing photos from my wife's account.

The photo I took is named "PXL_20250505_205025673" and cannot be found in the logs.  I do however see the photos from my wife's account in the logs.

docker-compopse.yaml:
````
version: "3.8"

services:
  immich-stack:
    container_name: immich_stack_colin
    # Use Docker Hub image (recommended for Portainer)
    image: majorfi/immich-stack:main # or :latest after next release
    # Or use GitHub Container Registry
    # image: ghcr.io/majorfi/immich-stack:latest
    environment:
      - API_KEY=${API_KEY}
      - API_URL=${API_URL:-http://immich-server:2283/api}
      - DRY_RUN=${DRY_RUN:-false}
      - RESET_STACKS=${RESET_STACKS:-false}
      - CONFIRM_RESET_STACK=${CONFIRM_RESET_STACK}
      - REPLACE_STACKS=${REPLACE_STACKS:-false}
      - PARENT_FILENAME_PROMOTE=${PARENT_FILENAME_PROMOTE:-edit}
      - PARENT_EXT_PROMOTE=${PARENT_EXT_PROMOTE:-.jpg,.dng}
      - WITH_ARCHIVED=${WITH_ARCHIVED:-false}
      - WITH_DELETED=${WITH_DELETED:-false}
      - RUN_MODE=${RUN_MODE:-once}
      - CRON_INTERVAL=${CRON_INTERVAL:-86400}
    volumes:
      - ./logs:/app/logs
    restart: on-failure
````
